class Database():
    def get_words_by_tag(self, tag):
        # something
        return [
            'Caccia',
            'Boccaglio',
            'Coraggioso',
            'Dispositivo',
            'Burro',
            'Caramelle',
            'Attacco',
            'Cianuro',
            'Albero',
            'Risciacquare',
            'Rotto',
            'Esercizio',
            'Gioiello',
            'Intonaco',
            'Costoso',
            'Bacio',
            'Zecca',
            'Zingaro',
            'Peruviana',
            'Mimare',
            'Affitto',
            'Twist',
            'Vivo',
            'Segare',
            'Punizione',
            'Scienza',
            'Anestesia',
            'Macchina',
            'Cellulare',
            'Musicista'
            ]